### ISSUE TITLE
wire:loading not working

### ISSUE THREAD

**Issue by jason18505** [wire-elements/wire-extender#11]
I couldn't get wire:loading to work. Just throwing this code into a component...

`<div wire:loading>show on click</div>`

and it always shows.

Really like this idea. Nice work!

**Comment by PhiloNL** [comment]
Let me know if it works now 😄 

- https://github.com/wire-elements/wire-extender/pull/16
- https://github.com/wire-elements/wire-extender/releases/tag/v0.0.6

**Comment by jason18505** [comment]
Perfect. Thanks for the quick turnaround.

**Comment by andrepolo** [comment]
I've installed v0.0.6, but it's still doing nothing. The loading div always shows.

**Comment by jason18505** [comment]
> I've installed v0.0.6, but it's still doing nothing. The loading div always shows.

I had to publish the js file again.

php artisan vendor:publish --tag=wire-extender
