### ISSUE TITLE
Question: is AlpineJS automatically available?

### ISSUE THREAD

**Issue by maltebaer** [wire-elements/wire-extender#17]
Hey @PhiloNL,

Sorry to bother you since I have more of a question than an issue. Is AlpineJS automatically available once we include the asset?

```html
<script src="https://unpkg.com/@wire-elements/wire-extender" data-uri="https://wire-elements.dev"></script>
```

I'm getting quite confused as I tried to include Alpine via

```blade
@assets
    <script
        defer
        src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"
    ></script>
@endassets
```

The weird part is, that Alpine is working but I can't find it included in my `<head>` tag. I could understand that it is working out of the box since Livewire relies on it. But then there is a bug in Livewire, since it does not show up in the `<head>` tag?! 😕

**Comment by PhiloNL** [comment]
Hi @maltebaer,
Alpine is part of Livewire v3 so there is no need to load Alpine manually as an asset (this will likely also result into conflicts). So `livewire.js` includes Alpine, that's is why it doesn't show up in the `<head>` tag.

**Comment by maltebaer** [comment]
Thanks for the quick reply, that makes sense.

One weird thing tough, if you include a script after `@vite()` it does not make it into the header. So better do

```blade
@assets
    <script
        src="https://cdn.jsdelivr.net/npm/pikaday/pikaday.js"
        defer
    ></script>
    @vite('resources/css/components/chatbot.css')
@endassets
```

and not the other way around. Maybe it'll help someone else.

**Comment by PhiloNL** [comment]
No problem. Not sure about the `@vite` problem though, I've never used `@assets` together with `@vite`.
