### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by flatcapco** [wire-elements/wire-extender#18]
Hi this looks great thanks but I'm struggling a bit with the documentation, 

It shows the view doesn't use a layout. and when using a layout it appears to be ignored is this the expected functionality?

Using @assets and @scripts within the blade view doesn't seem to work for me on l10 and latest livewire ie they just dont get loaded in.

PS there is a typo of Livewire 10 and Livewire 11 instead of Laravel X in the how to example

Thank you

**Comment by flatcapco** [comment]
Sorry last point was I'm not sure if using @vite is supported also for the loading of the main app.js and app.css because of not being able to use the layouts?

**Comment by PhiloNL** [comment]
Hi @flatcapco,

Thanks for giving Wire Extender a try! So Wire Extender is made to only embed non-full-page components. Layouts are only used when using full-page components so for that reason it will not work. Assets and scripts should work fine.

I think Vite should work but again, only when using regular components.

**Comment by flatcapco** [comment]
Thanks Phil. That makes sense, I couldn’t get the assets and scripts to
work inline using the @ tags . I’m going to set up a simplified component
to see if I can replicate the issue. Ps love the other work you’re doing

**Comment by flatcapco** [comment]
Hey sorry, I've just replicated the counter example and can confirm the @script and @assets isn't being pulled in.
The counter displays but has no interactivity/styling due to the missing assets and scripts

PHP 8.2
Laravel 10.48.12
Livewire 3.5
Extender 0.0.6

Anything I can do to help with this?

**Comment by dircm** [comment]
Hi @flatcapco can you get a screenshot of the browser network traffic when you refresh the page you re trying to load the component on ?  Should look something like this :

![image](https://github.com/wire-elements/wire-extender/assets/18188561/6c07c530-1482-402c-8539-778443063d53)

**Comment by flatcapco** [comment]
Hey @dircm thanks - stupidly I forgot to check this - it looks like : https://xxx.test/livewire/livewire.min.js is being blocked:
https://capture.dropbox.com/MUQN61oQVAlL26bd

I've followed the laravel10 steps to a tee:

Cors:
```
    'paths'           => ['api/*', 'sanctum/csrf-cookie', 'horizon/*', 'livewire/*'],
```

```
class VerifyCsrfToken extends Middleware
{
    use IgnoreForWireExtender;

    protected $except = [
        'livewire/*',
      ...
```


Can I just confirm this step is Laravel 11 only:

```php
 
use App\Http\Middleware\VerifyCsrfToken as CustomVerifyCsrfToken;
use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;
use Illuminate\Foundation\Http\Middleware\ValidateCsrfToken;
 
return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__.'/../routes/web.php',
        commands: __DIR__.'/../routes/console.php',
        health: '/up',
    )
    ->withMiddleware(function (Middleware $middleware) {
        $middleware->web(replace: [
            ValidateCsrfToken::class => CustomVerifyCsrfToken::class,
        ]);
    })
    ->withExceptions(function (Exceptions $exceptions) {
        //
    })->create();

```

**Comment by dircm** [comment]
> Hey @dircm thanks - stupidly I forgot to check this - it looks like : https://xxx.test/livewire/livewire.min.js is being blocked:
> 
> https://capture.dropbox.com/MUQN61oQVAlL26bd
> 
> 
> 
> I've followed the laravel10 steps to a tee:
> 
> 
> 
> Cors:
> 
> ```
> 
>     'paths'           => ['api/*', 'sanctum/csrf-cookie', 'horizon/*', 'livewire/*'],
> 
> ```
> 
> 
> 
> ```
> 
> class VerifyCsrfToken extends Middleware
> 
> {
> 
>     use IgnoreForWireExtender;
> 
> 
> 
>     protected $except = [
> 
>         'livewire/*',
> 
>       ...
> 
> ```
> 
> 
> 
> 
> 
> Can I just confirm this step is Laravel 11 only:
> 
> 
> 
> ```php
> 
>  
> 
> use App\Http\Middleware\VerifyCsrfToken as CustomVerifyCsrfToken;
> 
> use Illuminate\Foundation\Application;
> 
> use Illuminate\Foundation\Configuration\Exceptions;
> 
> use Illuminate\Foundation\Configuration\Middleware;
> 
> use Illuminate\Foundation\Http\Middleware\ValidateCsrfToken;
> 
>  
> 
> return Application::configure(basePath: dirname(__DIR__))
> 
>     ->withRouting(
> 
>         web: __DIR__.'/../routes/web.php',
> 
>         commands: __DIR__.'/../routes/console.php',
> 
>         health: '/up',
> 
>     )
> 
>     ->withMiddleware(function (Middleware $middleware) {
> 
>         $middleware->web(replace: [
> 
>             ValidateCsrfToken::class => CustomVerifyCsrfToken::class,
> 
>         ]);
> 
>     })
> 
>     ->withExceptions(function (Exceptions $exceptions) {
> 
>         //
> 
>     })->create();
> 
> 
> 
> ```

Ok then first thing is to check your APP_DEBUG is set to false.  See here : https://github.com/wire-elements/wire-extender/issues/4#issuecomment-2028836952

**Comment by flatcapco** [comment]
jeez yep that did it... what a silly miss I just noticed that the none minified version worked at the same time. thanks for getting me over the line!

**Comment by dircm** [comment]
> jeez yep that did it... what a silly miss I just noticed that the none minified version worked at the same time. thanks for getting me over the line!

Dont worry, it has bitten a few of us !

**Comment by flatcapco** [comment]
Think it needs a big red box in the docs :D
