### ISSUE TITLE
I try and embeddable other site but it not showing

### ISSUE THREAD

**Issue by daolvcntt** [wire-elements/wire-extender#19]
I've  console.log in function render components and nothing components render here. Could you help me?
![image](https://github.com/wire-elements/wire-extender/assets/3265966/c3ec0cf9-6092-4608-bc1b-ed39236b5c7a)
My request params has values
<img width="882" alt="image" src="https://github.com/wire-elements/wire-extender/assets/3265966/6802a0f1-6c36-4722-b6f8-c229e916ffef">
and response empty 
<img width="840" alt="image" src="https://github.com/wire-elements/wire-extender/assets/3265966/01ad5664-bbb8-4f60-899e-c60b30a66935">

**Comment by PhiloNL** [comment]
Can you verify that your component is using the embedabble trait.

**Comment by daolvcntt** [comment]
> Can you verify that your component is using the embeddable trait.

@PhiloNL "I added the Embeddable trait to the component." 
![image](https://github.com/wire-elements/wire-extender/assets/3265966/18f44913-b251-40ca-9d00-d711c35fd298)

**Comment by daolvcntt** [comment]
@PhiloNL I could render and display the elements, but I encountered other issues as I could not interact with them (meaning they were not responsive to events).

- The Root component I see is "widgets\/counter" but the embed component path is "livewire\/embed". I don't know it is a problem. How to change that?
<img width="1016" alt="image" src="https://github.com/wire-elements/wire-extender/assets/3265966/bfa19b8f-7522-4c56-a33d-a1a5e0e81ffe">

Embed component
<img width="1000" alt="image" src="https://github.com/wire-elements/wire-extender/assets/3265966/b69ff7a4-1c1d-4d52-8a72-1909ece0bcbd">
