### ISSUE TITLE
URL params are not recognised

### ISSUE THREAD

**Issue by andrepolo** [wire-elements/wire-extender#21]
If you use the `#[Url]` attribute on a property in a Livewire-Component, this property is added to the URL. When you refresh the page you'd expect this param to be recognised by Livewire, but it doesn't. It works in a regular component, but when embedded using this wonderful package, it's not.

**Comment by andrepolo** [comment]
Is there anything wrong with what i've wrote? I'm not a native english speaker. Or don't you understand the problem? Let me know.

**Comment by PhiloNL** [comment]
Thanks for reporting. I've haven't had the chance to look into this yet.

**Comment by PhiloNL** [comment]
This should now work @andrepolo 😄
