### ISSUE TITLE
Component Displaying as [object Object]

### ISSUE THREAD

**Issue by jsznap** [wire-elements/wire-extender#24]
Using an exact copy from the documentation (triple checked all steps), trying to display the counter demo component shows on the page as [object Object] in text. Any livewire configurations that I need to check?

Response from the embed request
`{"components":{"counter":{}},"assets":[]}`

Component:
```
<?php

namespace App\Livewire;

use Livewire\Component;
use WireElements\WireExtender\Attributes\Embeddable;

#[Embeddable]
class Counter extends Component
{
    public $count = 0;

    public function increment()
    {
        $this->count++;
    }

    public function decrement()
    {
        $this->count--;
    }

    public function render()
    {
        return view('livewire.counter');
    }
}
```

**Comment by PhiloNL** [comment]
Hi @jsznap 
Given the API is not returning anything I would recommend double-checking the CSRF settings and ensuring the `IgnoreForWireExtender` trait is loaded.
