### ISSUE TITLE
Feature discussion - asset versioning

### ISSUE THREAD

**Issue by dircm** [wire-elements/wire-extender#26]
I use wire-extender to create widgets that my customers can place into their own sites.  I have no control over other elements on the page where the widget is used.

When an update to the wire-extender.js file is made we run into the issue of browser caching older versions of the js file.

I don't want to ask my customers to manually update their widget code (e.g. add a ?v=1.0 to the js file reference)

What other strategies can anyone come up with to solve this ?

**Comment by PhiloNL** [comment]
One way to solve this is by setting a custom expires header. For example, if you use Nginx, you could use a config like:

```
location ~* \.js$ {
    expires 1h;
    add_header Cache-Control "public";
}
```

This way, the browser will always get the latest version every hour.

**Comment by dircm** [comment]
Thanks @PhiloNL !

Following on from your suggestion and after some reading...  I'll try this approach:

Since my Nginx setup (via Forge) sets the `last-modified` date already, I'll adopt the `no-cache` setting for `Cache-Control`.

`no-cache` means the browser **will** cache the JS file but will perform a check on the age of the file on each request.  Some performance tests didnt show any impact on the overall experience of the widgets.

using this approach means the browsers _should_ always fetch the latest JS if it has changed....

```
location ~* ^/vendor/wire-elements/.*\.js$ {
    add_header Cache-Control "no-cache";
}
```

**Comment by dircm** [comment]
And I can confirm the above Nginx configuration works perfectly on both OPCache and Octane server environments.  Thanks for the help, Tom.
