### ISSUE TITLE
Wrong publish path

### ISSUE THREAD

**Issue by MasterZydra** [wire-elements/wire-extender#6]
Hi,

I noticed that the command `php artisan vendor:publish --tag=wire-extender` published the `wire-extender.js` to the wrong folder.

According to your documentation it should be in `public/vendor/wire-elements/js`, but the command publishes it in `public/vendor/wire-elements`.

Changing `WireExtenderServiceProvider.php` fixed it for me:
``` PHP
// Line 29
// From:
__DIR__.'/../js' => public_path('vendor/wire-elements'),
// To
__DIR__.'/../js' => public_path('vendor/wire-elements/js'),
```

**Comment by PhiloNL** [comment]
Thanks! I've updated the docs instead so it can remain to be `vendor/wire-elements`.
